### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by willvlad** [Azure-Samples/documentdb-node-todo-app#1]
When running npm start, the following error shows:
`

> Todo@0.0.0 start C:\Users\v\Dropbox\Dev\DOCDB\documentdb-node-todo-app\src
> node ./bin/www

module.js:442
    throw err;
    ^

Error: Cannot find module 'C:\Users\v\Dropbox\Dev\DOCDB\documentdb-node-todo-app\src\bin\www'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! Todo@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Todo@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Todo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Todo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Todo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\v\Dropbox\Dev\DOCDB\documentdb-node-todo-app\src\node_modules\npm-debug.log
`

**Comment by coatsnmore** [comment]
It looks like they didn't commit the bin/www file that is generated by express and contains all the express stuff.
